Add mentoring post for 26th Jan 2021
EmakinaFR/EmakinaFR.github.io pull request #10
Opened 2021-01-22 10:37 UTC by akiavara

Article preview:
![article_mentoring](https://user-images.githubusercontent.com/757106/105480462-131e2000-5ca6-11eb-97a4-18ef0effebb6.jpg)

2021-01-22 10:51 UTC, chloeavoustin approved these changes

2021-01-22 10:55 UTC, matthieupetel requested changes

2021-01-22 10:55 UTC, matthieupetel commented on _posts/2021-01-26-notre-systeme-de-mentoring.markdown
> +Un des grands défis d’une entreprise est de bien accueillir ses nouveaux collaborateurs. Cette tâche est d’autant plus ardue lorsque ladite entreprise possède des locaux dans différentes géolocalisat
Typo -> "géolocalisationS"

2021-01-22 10:55 UTC, matthieupetel commented on _posts/2021-01-26-notre-systeme-de-mentoring.markdown
> +L'intégration a été plus difficile socialement n’ayant été qu’une demie journée dans les bureaux pour récupérer mon matériel. J’ai tout de même été agréablement surpris de la rapidité avec laquelle j
Typo -> "je me suis senti"

2021-01-22 10:55 UTC, matthieupetel commented on _posts/2021-01-26-notre-systeme-de-mentoring.markdown
> +Magento est une technologie que je n’ai jamais utilisé jusqu’à présent et pouvoir bénéficier de l’aide de l’équipe ou de son mentor est vraiment bénéfique.
Typo -> "je n’ai jamais utiliséE"

2021-01-25 08:29 UTC, mignotl approved these changes

2021-01-25 10:30 UTC, matthieupetel approved these changes

2021-01-25 10:42 UTC, djino87 approved these changes

2021-01-26 09:20 UTC, merged